### ISSUE TITLE
Destination URL must name a directory, bucket, or bucket

### ISSUE THREAD

**Issue by botcs** [hammoudhasan/CLDatasets#1]
Hey @hammoudhasan thanks for the nice project!

when trying to download the dataset I get the following error:
```
subdirectory for the multiple source form of the cp command.
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
^CException in UIThread: 
```

**Comment by hammoudhasan** [comment]
Hello @botcs ! Thank you for your interest in that work.

Did you do step 0 ? authentication to GCP step? Also can you let me know which dataset are you trying to install?

**Comment by botcs** [comment]
yep, I did, although this was the response I got:
```
Enter authorization code: *****
                                                                                                                                                                                                           
Credentials saved to file: [/homes/53/csbotos/.config/gcloud/application_default_credentials.json]                                                                                                         
                                                                                                                                                                                                           
These credentials will be used by any library that requests Application Default Credentials (ADC).                                                                                                         
WARNING:                                                                                                                                                                                                   
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.
```

I had to install a local version of gcloud through [link](https://cloud.google.com/sdk/docs/downloads-interactive), so my version for gcloud is:
```
$ gcloud --version

Google Cloud SDK 434.0.0
bq 2.0.93
bundled-python3-unix 3.9.16
core 2023.06.02
gcloud-crc32c 1.0.0
gsutil 5.24
```

I was trying to download the CLOC dataset

**Comment by hammoudhasan** [comment]
Can you trying doing:

```
pip install gsutil
gsutil config
```

Then try again?

Also are you working on Linux based system?

**Comment by drimpossible** [comment]
It might be a gsutil cp issue. Does this link help? https://github.com/GoogleCloudPlatform/gsutil/issues/1535

**Comment by drimpossible** [comment]
Okay, I setup GCloud on a fresh machine and tried to download from here directly: https://console.cloud.google.com/storage/browser/cl-datasets (clicking on the CLOC folder, download and then using that link). Can you try if this works?

**Comment by botcs** [comment]
I installed gsutil

however running `gsutil config` threw this error:

```
CommandException: OAuth2 is the preferred authentication mechanism with the Cloud SDK.
Run "gcloud auth login" to configure authentication, unless:
- You don't want gsutil to use OAuth2 credentials from the Cloud SDK,
  but instead want to manage credentials with .boto files generated by
  running "gsutil config"; in which case run "gcloud config set
  pass_credentials_to_gsutil false".
- You want to authenticate with an HMAC access key and secret, in
  which case run "gsutil config -a".
```

the original error still persists.

@drimpossible the page you cited suggests that the dest directory doesn't exist. Double checked, it does

**Comment by hammoudhasan** [comment]
@drimpossible can you try running the download code on your side and do the authentication step as well ?

**Comment by drimpossible** [comment]
Okay, so the destination is not an issue then! I'm trying to run the python script now and see what might be buggy. Thanks for actively testing things out.

**Comment by botcs** [comment]
haha, nw, once this script works it will save a lot of hair cells of mine ;)

**Comment by drimpossible** [comment]
Alrighty, was not a gsutil issue, I think it was a command one. Patched it, should work now! 

@hammoudhasan I merged the order file and data download into one, is that okay?

**Comment by hammoudhasan** [comment]
LGTM @drimpossible

**Comment by drimpossible** [comment]
@botcs could you check if the code works for you now?

**Comment by hammoudhasan** [comment]
@drimpossible can you please add the requirements to step 0 of the pipeline? eg. pip install gsutil etc.. since you just had it freshly setup this might be quick on your end.

**Comment by botcs** [comment]
yep, works!

add this link @drimpossible https://cloud.google.com/sdk/docs/downloads-interactive too for those who don't have `sudo` permission

very quick fix guys!
thanks

**Comment by hammoudhasan** [comment]
@botcs you used this for the authentication right?

**Comment by botcs** [comment]
@hammoudhasan sorry what do you mean?
