### ISSUE TITLE
32k Missing paths in CGLM order_files

### ISSUE THREAD

**Issue by botcs** [hammoudhasan/CLDatasets#3]
Hi,

there's 32 214 paths are missing or have broken link in CGLM (in the train split at least).
You can find the broken paths here (CSV:index path)
https://gist.github.com/botcs/4b2b78b5b77699f02870d203c68a0262

Could you update them please?

Thanks,
Csabi

**Comment by hammoudhasan** [comment]
@botcs on it let me try to reproduce the error on my side. I will download the dataset locally and check if the files are missing.

**Comment by hammoudhasan** [comment]
@botcs could you please verify the issue is solved? It seems some of the order files had the prefix "/train/" and were not cleaned earlier.

**Comment by botcs** [comment]
@hammoudhasan should I check now?
majority of the paths were just missing - only from 462848 (L29941 in the file I've attached) onwards you can see the /train/ prefix causing the issue.

let me know if this is amended and I will re-download the header files
